[theme]
base="light"
primaryColor="#00fff9"
secondaryBackgroundColor="#f5f5f5"
textColor="#000000"
font="monospace"

[global]
layout = "default"
hideStreamlitFooter = true

[runner]
toolbarMode = "minimal"

